name: Build and Push xpense-service

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v3.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Clean
        run: bash limebrew-ci-scripts/scripts/ci/maven-clean.sh ${{ github.run_number }}

      - name: Build
        run: bash limebrew-ci-scripts/scripts/ci/maven-build.sh ${{ github.run_number }}

      - name: Push to Artifact Registry
        run: |
          export MAVEN_SECRET=${{ secrets.MAVEN_ARTIFACT_CREDENTIALS }}
          bash limebrew-ci-scripts/scripts/ci/build-push-maven.sh ${{ github.run_number }}

      - name: Build and push docker artifact
        run: bash limebrew-ci-scripts/scripts/ci/build-push-docker.sh xpense-service