name: Build and Push xpense-service

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Cache
        uses: actions/cache@v3.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Clean
        run: bash limebrew-ci-scripts/scripts/ci/maven-clean.sh ${{ github.run_number }}

      - name: Build
        run: bash limebrew-ci-scripts/scripts/ci/maven-build.sh ${{ github.run_number }}

      - name: Push to Maven artifact repository
        run: |
          export MAVEN_ARTIFACT_CREDENTIALS=${{ secrets.MAVEN_ARTIFACT_CREDENTIALS }}
          bash limebrew-ci-scripts/scripts/ci/build-push-maven.sh ${{ github.run_number }}

      - name: Build and push Docker artifact repository
        run: |
          export GCLOUD_ENCODED_SERVICE_ACCOUNT_JSON=${{ secrets.GCLOUD_ENCODED_API_KEY_LIMEBREW }}
          export GCLOUD_DOCKER_REPO_HOST_NAME=${{ secrets.GCLOUD_DOCKER_REGISTRY_HOSTNAME }}
          export GCLOUD_PROJECT_ID=${{ secrets.GCLOUD_PROJECT_ID_LIMEBREW }}
          export GCLOUD_DOCKER_REPO_NAME=${{ secrets.GCLOUD_DOCKER_REPO_NAME }}
          export SERVICE_IMAGE_NAME=xpense-service
          export TAG_NAME=1.0.${{ github.run_number }}
          bash limebrew-ci-scripts/scripts/ci/build-push-docker.sh